### ISSUE TITLE
EdXposed manager crashes when attempting Canary install

### ISSUE THREAD

**Issue by cloudnsephiroth** [ElderDrivers/EdXposedManager#208]
###### Include the following:
 - EdXposed Version: `v0.5.2.2_4683-master`
 - Android Version: `11`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Poco F2 Pro`
 - EdXposed Manager Version: `4.6.2`
 
###### Reproduction Steps

1. Load EdXposed manager (framework is active)
2. Go to Canary tab
3. Press install/update
4. Press OK on prompt

###### Expected Result
Canary drivers to download

###### Actual Result
EdXposed manager crashes without downloading

**Comment by Ikikass** [comment]
I have the same problem.  Here is the crash log.

BOARD=sdm845
CPU_ABI2=
HOST=rd-build-71
versionName=4.6.2
IS_TREBLE_ENABLED=true
SUPPORTED_64_BIT_ABIS=[arm64-v8a]
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
IS_USERDEBUG=false
DISPLAY=ONEPLUS A6013_41_210511
SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
FINGERPRINT=google/walleye/walleye:10/QQ1A.200205.002/6084386:user/release-keys
PRODUCT=OnePlus6T
ID=QKQ1.190716.003
TYPE=user
SERIAL=unknown
IS_CONTAINER=false
IS_ENG=false
SOFT_VERSION=J.54
DEVICE=OnePlus6T
TIME=1620742947000
IS_USER=true
MODEL=ONEPLUS A6013
MANUFACTURER=OnePlus
USER=jenkins
versionCode=46200
BRAND=OnePlus
REGION=OverSeas
SUPPORTED_32_BIT_ABIS=[armeabi-v7a, armeabi]
HARDWARE=qcom
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
AUTO_TEST_ONEPLUS=false
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=false
DEBUG_ONEPLUS=false
TAGS=release-keys
java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.meowcat.edxposed.manager.util.json.XposedZip.name' on a null object reference
	at org.meowcat.edxposed.manager.-$$Lambda$BaseAdvancedInstaller$OzsXQWD6GeVrRZwKo4x9skW4lac.onClick(lambda:3)
	at android.view.View.performClick(View.java:7201)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27562)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
