### ISSUE TITLE
Crash when opening app

### ISSUE THREAD

**Issue by carrsteven** [ElderDrivers/EdXposedManager#42]
###### Include the following:
 - Xposed Version: `magisk-EdXposed-SandHook-v0.4.5.5_beta(4470)` 
 - [ ] Xposed Systemless
 - Device OS version: `10'
 - Device Manufacturer: `Google`
 - Device Name: `Pixel 3XL`
 - Material Xposed Installer version: `4.5.0` or `4.5.1`
 
###### Reproduction Steps

1. Install EdXposed Manager
2. Open App
3. App Crashes

###### Expected Result
App opens.

###### Actual Result
App crashes after opening.

###### Log Copy/Pasted

BOARD=crosshatch
CPU_ABI2=
HOST=abfarm801
versionName=4.5.0
IS_TREBLE_ENABLED=true
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@7f22a80
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
IS_USERDEBUG=false
DISPLAY=QP1A.190711.020
SUPPORTED_ABIS=[Ljava.lang.String;@a0f48b9
FINGERPRINT=google/crosshatch/crosshatch:10/QP1A.190711.020/5800535:user/release-keys
PRODUCT=crosshatch
ID=QP1A.190711.020
TYPE=user
SERIAL=unknown
IS_CONTAINER=false
IS_ENG=false
DEVICE=crosshatch
TIME=1565794403000
IS_USER=true
MODEL=Pixel 3 XL
MANUFACTURER=Google
USER=android-build
versionCode=450
BRAND=google
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@285eb03
HARDWARE=crosshatch
IS_DEBUGGABLE=false
BOOTLOADER=b1c1-0.2-5672671
RADIO=unknown
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at de.robv.android.xposed.installer.installation.BaseAdvancedInstaller.onCreateView(BaseAdvancedInstaller.java:157)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2595)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:880)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1237)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1302)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2655)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2609)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:903)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1237)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1302)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2655)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2609)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
	at android.app.Activity.performStart(Activity.java:7825)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by carrsteven** [comment]
Removing SandHook and installing YAHFA fixed the issue.
