### ISSUE TITLE
EdXposedManager crash immediately when open

### ISSUE THREAD

**Issue by shenzhigang** [ElderDrivers/EdXposedManager#68]
###### Include the following:
 - EdXposed Version: `0.4.6.2(4529)(YAHFA)`
 - Android Version: `9`
 - Device Manufacturer: `Lenovo`
 - Device Name: `Z5`
 - EdXposed Manager Version: `4.5.6`
 
###### Reproduction Steps

1. Open EdXposedManager
2. Crash immediately

###### Logs in logcat
```
2020-04-02 22:07:08.039 11948-11948/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.meowcat.edxposed.manager, PID: 11948
    java.lang.ExceptionInInitializerError
        at org.meowcat.edxposed.manager.repo.RepoDb.beginTransation(RepoDb.java:59)
        at org.meowcat.edxposed.manager.util.ModuleUtil.reloadInstalledModules(ModuleUtil.java:89)
        at org.meowcat.edxposed.manager.util.ModuleUtil.getInstance(ModuleUtil.java:64)
        at org.meowcat.edxposed.manager.XposedApp.onCreate(XposedApp.java:225)
        at org.meowcat.edxposed.manager.MeowCatApplication.onCreate(MeowCatApplication.java:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5994)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:163)
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:304)
        at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:198)
        at android.app.ActivityThread.access$1100(ActivityThread.java:204)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
        at org.meowcat.edxposed.manager.repo.RepoDb.getRepositories(RepoDb.java:107)
        at org.meowcat.edxposed.manager.util.RepoLoader.refreshRepositories(RepoLoader.java:84)
        at org.meowcat.edxposed.manager.util.RepoLoader.<init>(RepoLoader.java:74)
        at org.meowcat.edxposed.manager.util.RepoLoader.getInstance(RepoLoader.java:79)
        at org.meowcat.edxposed.manager.repo.RepoDb.onCreate(RepoDb.java:450)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:393)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at org.meowcat.edxposed.manager.repo.RepoDb.<clinit>(RepoDb.java:44)
        at org.meowcat.edxposed.manager.repo.RepoDb.beginTransation(RepoDb.java:59) 
        at org.meowcat.edxposed.manager.util.ModuleUtil.reloadInstalledModules(ModuleUtil.java:89) 
        at org.meowcat.edxposed.manager.util.ModuleUtil.getInstance(ModuleUtil.java:64) 
        at org.meowcat.edxposed.manager.XposedApp.onCreate(XposedApp.java:225) 
        at org.meowcat.edxposed.manager.MeowCatApplication.onCreate(MeowCatApplication.java:18) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5994) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185) 
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:163) 
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:304) 
        at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:198) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:204) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6820) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861) 
```

**Comment by UltraBlackLinux** [comment]
Its crashing too on my phone:
`04-02 18:53:07.270  2102 14725 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.meowcat.edxposed.manager/.WelcomeActivityMlgmXyysd bnds=[1128,670][1400,1040]} from uid 10102
04-02 18:53:07.282  2102  2223 E system_server: Invalid ID 0x00000000.
04-02 18:53:07.290  1891  1891 D Zygote  : Forked child process 15484
04-02 18:53:07.296  2102  2231 I ActivityManager: Start proc 15484:org.meowcat.edxposed.manager/u0a143 for activity {org.meowcat.edxposed.manager/org.meowcat.edxposed.manager.WelcomeActivityMlgmXyysd}
04-02 18:53:07.308 15484 15484 E dxposed.manage: Not starting debugger since process cannot load the jdwp agent.
04-02 18:53:07.340 15484 15484 I dxposed.manage: The ClassLoaderContext is a special shared library.
04-02 18:53:07.368 15484 15484 D AndroidRuntime: Shutting down VM
04-02 18:53:07.369 15484 15484 E AndroidRuntime: FATAL EXCEPTION: main
04-02 18:53:07.369 15484 15484 E AndroidRuntime: Process: org.meowcat.edxposed.manager, PID: 15484
04-02 18:53:07.369 15484 15484 E AndroidRuntime: java.lang.ExceptionInInitializerError
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.repo.RepoDb.beginTransation(RepoDb.java:59)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.util.ModuleUtil.reloadInstalledModules(ModuleUtil.java:89)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.util.ModuleUtil.getInstance(ModuleUtil.java:64)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.XposedApp.onCreate(XposedApp.java:225)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.MeowCatApplication.onCreate(MeowCatApplication.java:18)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-02 18:53:07.369 15484 15484 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.repo.RepoDb.getRepositories(RepoDb.java:107)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.util.RepoLoader.refreshRepositories(RepoLoader.java:84)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.util.RepoLoader.<init>(RepoLoader.java:74)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.util.RepoLoader.getInstance(RepoLoader.java:79)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.repo.RepoDb.onCreate(RepoDb.java:450)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:412)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        at org.meowcat.edxposed.manager.repo.RepoDb.<clinit>(RepoDb.java:44)
04-02 18:53:07.369 15484 15484 E AndroidRuntime:        ... 15 more
04-02 18:53:07.370  2102 15508 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
04-02 18:53:07.370  2102 12519 W ActivityTaskManager:   Force finishing activity org.meowcat.edxposed.manager/.WelcomeActivityMlgmXyysd
04-02 18:53:07.373 15484 15484 I Process : Sending signal. PID: 15484 SIG: 9
04-02 18:53:07.380  2102 12519 I ActivityManager: Process org.meowcat.edxposed.manager (pid 15484) has died: fore TOP 
04-02 18:53:07.380  2102  2232 I libprocessgroup: Successfully killed process cgroup uid 10143 pid 15484 in 0ms
04-02 18:53:07.381  1891  1891 I Zygote  : Process 15484 exited due to signal 9 (Killed)
04-02 18:53:07.806   649   649 E Layer   : [Surface(name=AppWindowToken{632c8f7 token=Token{97aacf6 ActivityRecord{869b591 u0 org.meowcat.edxposed.manager/.WelcomeActivityMlgmXyysd t109}}})/@0x488c0b - animation-leash#0] No local sync point found
04-02 18:53:07.806   649   649 E Layer   : [Surface(name=AppWindowToken{e7118f token=Token{716d8ee ActivityRecord{99bb669 u0 com.android.launcher3/.lineage.LineageLauncher t2}}})/@0x9a6e08f - animation-leash#0] No local sync point found
04-02 18:53:07.814   649   649 E Layer   : [Surface(name=AppWindowToken{632c8f7 token=Token{97aacf6 ActivityRecord{869b591 u0 org.meowcat.edxposed.manager/.WelcomeActivityMlgmXyysd t109}}})/@0x488c0b - animation-leash#0] No local sync point found
04-02 18:53:07.814   649   649 E Layer   : [Surface(name=AppWindowToken{e7118f token=Token{716d8ee ActivityRecord{99bb669 u0 com.android.launcher3/.lineage.LineageLauncher t2}}})/@0x9a6e08f - animation-leash#0] No local sync point found
04-02 18:53:07.872  2102  2222 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{869b591 u0 org.meowcat.edxposed.manager/.WelcomeActivityMlgmXyysd t-1 f}
04-02 18:53:09.502   911  1214 I qti_sensors_hal: processReportInd: X: -0.062256 Y: 0.050278 Z: 9.856934
`

**Comment by UltraBlackLinux** [comment]
Its crashing too on Lineageos 17.1 (android 10)
![Screenshot_20200402_185536](https://user-images.githubusercontent.com/62404294/78276798-cfd6a300-7513-11ea-906a-25d95ffbeb55.png)
sry for screeenie, but else thee format is broken

**Comment by always1337** [comment]
Try installing over the old version, it helped me fix the crashes.

**Comment by kevin01523** [comment]
Same it crashes and i cant seem to overwrite the old with the new version

**Comment by Lvl4Sword** [comment]
Overwriting the previous version ( v4.5.6.0.0 ) with the new version ( v4.5.6.0.1 ) was what fixed the crashing for me.

**Comment by MlgmXyysd** [comment]
[EdXposedManager-4.5.6-45601-org.meowcat.edxposed.manager-debug.zip](https://github.com/ElderDrivers/EdXposedManager/files/4424740/EdXposedManager-4.5.6-45601-org.meowcat.edxposed.manager-debug.zip)

Can anyone test this? (Rename .zip to .apk)

do not overwrite previous version, clean install to test

ignore lagggg, cause it's debug version

**Comment by shenzhigang** [comment]
> [EdXposedManager-4.5.6-45601-org.meowcat.edxposed.manager-debug.zip](https://github.com/ElderDrivers/EdXposedManager/files/4424740/EdXposedManager-4.5.6-45601-org.meowcat.edxposed.manager-debug.zip)
> 
> Can anyone test this? (Rename .zip to .apk)
> 
> do not overwrite previous version, clean install to test
> 
> ignore lagggg, cause it's debug version

It works!

**Comment by MlgmXyysd** [comment]
> > [EdXposedManager-4.5.6-45601-org.meowcat.edxposed.manager-debug.zip](https://github.com/ElderDrivers/EdXposedManager/files/4424740/EdXposedManager-4.5.6-45601-org.meowcat.edxposed.manager-debug.zip)
> > Can anyone test this? (Rename .zip to .apk)
> > do not overwrite previous version, clean install to test
> > ignore lagggg, cause it's debug version
> 
> It works!

Well I know, will update in next version, thanks for test
