### ISSUE TITLE
Enhancement module checking for enabled_modules.list in userId -1

### ISSUE THREAD

**Issue by Firefds** [ElderDrivers/EdXposedManager#94]
###### Include the following:
 - EdXposed Version: `0.4.6.3 (4546)`
 - Android Version: `9`
 - Device Manufacturer: `Samsung`
 - Device Name: `S8`
 - EdXposed Manager Version: `4.5.7 (45700)`
 
###### Reproduction Steps

1. Enable enhancement module
2. Reboot
3. Check logs

###### Expected Result
No errors shown

###### Actual Result
```
04-19 10:11:33.200  3937  3976 I EdXposed-Bridge: EdXpMgrEx: Reading modules list /data/user_de/-1/org.meowcat.edxposed.manager/conf/enabled_modules.list...
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: java.io.FileNotFoundException: /data/user_de/-1/org.meowcat.edxposed.manager/conf/enabled_modules.list (No such file or directory)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at java.io.FileInputStream.open0(Native Method)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at java.io.FileInputStream.open(FileInputStream.java:231)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at java.io.FileInputStream.<init>(FileInputStream.java:165)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at java.io.FileReader.<init>(FileReader.java:72)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at org.meowcat.edxposed.manager.xposed.Enhancement.readModulesList(Enhancement.java:114)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at org.meowcat.edxposed.manager.xposed.Enhancement.getModulesList(Enhancement.java:101)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at org.meowcat.edxposed.manager.xposed.Enhancement.access$400(Enhancement.java:39)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at org.meowcat.edxposed.manager.xposed.Enhancement$4.beforeHookedMethod(Enhancement.java:267)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:110)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:250)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4768)
04-19 10:11:33.204  3937  3976 E EdXposed-Bridge: 	at android.os.Binder.execTransact(Binder.java:739)
```

**Comment by MlgmXyysd** [comment]
@Palatis
